### PR TITLE
Added `coordinate_precision.py`

### PR DESCRIPTION
**Pull request by HaydenElza**
Added `coordinate_precision.py` which reduces the coordinate precision of index dataset geojsons.

### CODE REVIEW

**Comment by HaydenElza** [comment]
Need to add argument for indentation/minified.

**Comment by Wiscmapper** [comment]
Suggest making -i more flexible...  bombs with lowercase none

```
(arcgispro-py3) d:\temp2>python r:\scripts\coordinate_precision.py geojsonin geojsonout -i none
Traceback (most recent call last):
  File "r:\scripts\coordinate_precision.py", line 109, in <module>
    else: raise TypeError('-i/--indent: invalid; must be int or None')
TypeError: -i/--indent: invalid; must be int or None

(arcgispro-py3) d:\temp2>python r:\scripts\coordinate_precision.py geojsonin geojsonout -i None
```

**Comment by Wiscmapper** [comment]
-i intended to be optional, but it's actually required or else script fails

```
(arcgispro-py3) d:\temp2>python r:\scripts\coordinate_precision.py geojsonin geojsonout
Traceback (most recent call last):
  File "r:\scripts\coordinate_precision.py", line 108, in <module>
    elif args.indentation.isdigit(): args.indentation=int(args.indentation)
AttributeError: 'int' object has no attribute 'isdigit'

(arcgispro-py3) d:\temp2>
```

**Comment by Wiscmapper** [comment]
Script is currently designed to work on polygons only.  Add ability to process points.  example: https://gisdata.wisc.edu/public/indexes/1930sAerials_Adams.geojson

**Comment by Wiscmapper** [comment]
Suggest making the default value for -i = None.  In most situations we want the most compact json possible.

**Comment by Wiscmapper** [comment]
... other than the issues noted above, it seems like it's working well!  The ability to handle points is most critical.

**Pull request merged**
